Add corona chart
TotalCross/embedded-samples pull request #8
Opened 2020-09-07 19:59 UTC by flsobral

add corona-chart sample
#3

2020-09-08 17:52 UTC, VaneskaSousa commented on corona-chart/src/main/java/com/totalcross/coronachart/RunCoronaChartApplication.java
> +                "/scr", "848x480", "/density", "1", "/r", "5443444B5AAEEB90306B00E4");
Please delete the comments and the TC Key

2020-09-08 17:53 UTC, VaneskaSousa requested changes
Just need to delete the TC Key from RunCoronaChartApplication.java

2020-09-10 12:06 UTC, acmlira commented on .github/workflows/ci.yml
> +              - corona-chart
Why not _CoronaChart_?

2020-09-23 13:28 UTC, VaneskaSousa approved these changes

2020-09-24 10:58 UTC, nmarquesin commented
@flsobral, could you please update the commit message to the correct format "<scope>: <subject>" with an optional body and footer separated by blank lines?

2020-10-01 17:28 UTC, VaneskaSousa commented
Hey, @flsobral what are missing to merge this branch?

2020-11-16 18:58 UTC, closed without merging

2020-11-16 18:59 UTC, flsobral commented
it's hammer time